### ISSUE TITLE
Ubuntu 14.04 installation

### ISSUE THREAD

**Issue by ninefineninja** [Ban3/python-evic#7] opened 2016-01-13 08:35 UTC
Hello! Thanks for your work!

I spent almost 6 hours trying to fix that, installing dependencies etc but no success.

Install script just gives me a bunch of errors about hid.pyx and hid.so, and in the end of output - ImportError: /usr/local/lib/python2.7/dist-packages/hid.so: undefined symbol: libusb_open.

Somehow I managed to solve these but I have recieved that:
  from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 3138, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 3124, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 661, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 962, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 849, in resolve
pkg_resources.DistributionNotFound: The 'hidapi>=0.7.99' distribution was not found and is required by evic

So, I guess the problem is somehow connected with hidapi. I tried different versions, tried cython-hidapi etc .

**Comment by ReservedField** [comment] 2016-01-13 16:19
I'm not the author, but maybe I can help... The `DistributionNotFound` means that setup didn't go to completion (hidapi wasn't installed). This is likely due to you missing libraries, as the undefined symbols show. Try:

```
sudo apt-get install python-dev libudev libusb-dev
sudo python setup.py install
```

**Comment by Ban3** [comment] 2016-01-13 16:48
When I was testing clean install on OSX it failed if cython wasn't installed before running setup.py. It's some kind of issue with hidapi. Cython should be available from Ubuntu repositories.

**Comment by ReservedField** [comment] 2016-01-13 17:00
> Cython should be available from Ubuntu repositories.

Via pip:

```
sudo apt-get install python-pip
sudo pip install cython
```

**Comment by ninefineninja** [comment] 2016-01-13 23:44
Thanks for your support! Unfortunately, the problem was not solved. Here is full log:

```
oesayan@oesayan-linux:~/python-evic$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to evic.egg-info/requires.txt
writing evic.egg-info/PKG-INFO
writing top-level names to evic.egg-info/top_level.txt
writing dependency_links to evic.egg-info/dependency_links.txt
writing entry points to evic.egg-info/entry_points.txt
reading manifest file 'evic.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no files found matching '*.rst' under directory '*'
warning: no files found matching 'Makefile' under directory '*'
writing manifest file 'evic.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/evic
copying build/lib.linux-x86_64-2.7/evic/binfile.py -> build/bdist.linux-x86_64/egg/evic
copying build/lib.linux-x86_64-2.7/evic/cli.py -> build/bdist.linux-x86_64/egg/evic
copying build/lib.linux-x86_64-2.7/evic/helpers.py -> build/bdist.linux-x86_64/egg/evic
copying build/lib.linux-x86_64-2.7/evic/__init__.py -> build/bdist.linux-x86_64/egg/evic
copying build/lib.linux-x86_64-2.7/evic/dataflash.py -> build/bdist.linux-x86_64/egg/evic
copying build/lib.linux-x86_64-2.7/evic/device.py -> build/bdist.linux-x86_64/egg/evic
byte-compiling build/bdist.linux-x86_64/egg/evic/binfile.py to binfile.pyc
byte-compiling build/bdist.linux-x86_64/egg/evic/cli.py to cli.pyc
byte-compiling build/bdist.linux-x86_64/egg/evic/helpers.py to helpers.pyc
byte-compiling build/bdist.linux-x86_64/egg/evic/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/evic/dataflash.py to dataflash.pyc
byte-compiling build/bdist.linux-x86_64/egg/evic/device.py to device.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying evic.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying evic.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying evic.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying evic.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying evic.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying evic.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/evic-0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing evic-0.1-py2.7.egg
Copying evic-0.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding evic 0.1 to easy-install.pth file
Installing evic script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/evic-0.1-py2.7.egg
Processing dependencies for evic==0.1
Searching for hidapi>=0.7.99
Reading https://pypi.python.org/simple/hidapi/
Best match: hidapi 0.7.99.post10
Downloading https://pypi.python.org/packages/source/h/hidapi/hidapi-0.7.99.post10.tar.gz#md5=5994cf542ef86a1a0df6829cdc0a08be
Processing hidapi-0.7.99.post10.tar.gz
Writing /tmp/easy_install-WTg0YY/hidapi-0.7.99.post10/setup.cfg
Running hidapi-0.7.99.post10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-WTg0YY/hidapi-0.7.99.post10/egg-dist-tmp-teOGTW

Error compiling Cython file:
------------------------------------------------------------
...
import sys
from chid cimport *
^
------------------------------------------------------------

hid.pyx:2:0: 'chid.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
    c = c.next
  hid_free_enumeration(info)
  return res

cdef class device:
  cdef hid_device *_c_hid
      ^
------------------------------------------------------------

hid.pyx:45:7: 'hid_device' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    return ''
  cdef int n = wcslen(wcs)
  return PyUnicode_FromWideChar(wcs, n)

def enumerate(int vendor_id=0, int product_id=0):
  cdef hid_device_info* info = hid_enumerate(vendor_id, product_id)
      ^
------------------------------------------------------------

hid.pyx:24:7: 'hid_device_info' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
  cdef int n = wcslen(wcs)
  return PyUnicode_FromWideChar(wcs, n)

def enumerate(int vendor_id=0, int product_id=0):
  cdef hid_device_info* info = hid_enumerate(vendor_id, product_id)
  cdef hid_device_info* c = info
      ^
------------------------------------------------------------

hid.pyx:25:7: 'hid_device_info' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
      # convert to bytes
      if sys.version_info < (3, 0):
          buff = ''.join(map(chr, buff))
      else:
          buff = bytes(buff)
      cdef hid_device * c_hid = self._c_hid
          ^
------------------------------------------------------------

hid.pyx:88:11: 'hid_device' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
          raise ValueError('not open')
      cdef unsigned char lbuff[16]
      cdef unsigned char* cbuff
      cdef size_t c_max_length = max_length
      cdef int c_timeout_ms = timeout_ms
      cdef hid_device * c_hid = self._c_hid
          ^
------------------------------------------------------------

hid.pyx:110:11: 'hid_device' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
      # convert to bytes
      if sys.version_info < (3, 0):
          buff = ''.join(map(chr, buff))
      else:
          buff = bytes(buff)
      cdef hid_device * c_hid = self._c_hid
          ^
------------------------------------------------------------

hid.pyx:161:11: 'hid_device' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
      return result

  def get_feature_report(self, int report_num, int max_length):
      if self._c_hid == NULL:
          raise ValueError('not open')
      cdef hid_device * c_hid = self._c_hid
          ^
------------------------------------------------------------

hid.pyx:172:11: 'hid_device' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    return ''
  cdef int n = wcslen(wcs)
  return PyUnicode_FromWideChar(wcs, n)

def enumerate(int vendor_id=0, int product_id=0):
  cdef hid_device_info* info = hid_enumerate(vendor_id, product_id)
                                           ^
------------------------------------------------------------

hid.pyx:24:44: undeclared name not builtin: hid_enumerate

Error compiling Cython file:
------------------------------------------------------------
...
  while c:
    res.append({
      'path': c.path,
      'vendor_id': c.vendor_id,
      'product_id': c.product_id,
      'serial_number': U(c.serial_number),
                         ^
------------------------------------------------------------

hid.pyx:32:26: Cannot convert Python object to 'wchar_t *'

Error compiling Cython file:
------------------------------------------------------------
...
      'path': c.path,
      'vendor_id': c.vendor_id,
      'product_id': c.product_id,
      'serial_number': U(c.serial_number),
      'release_number': c.release_number,
      'manufacturer_string': U(c.manufacturer_string),
                               ^
------------------------------------------------------------

hid.pyx:34:32: Cannot convert Python object to 'wchar_t *'

Error compiling Cython file:
------------------------------------------------------------
...
      'vendor_id': c.vendor_id,
      'product_id': c.product_id,
      'serial_number': U(c.serial_number),
      'release_number': c.release_number,
      'manufacturer_string': U(c.manufacturer_string),
      'product_string': U(c.product_string),
                          ^
------------------------------------------------------------

hid.pyx:35:27: Cannot convert Python object to 'wchar_t *'

Error compiling Cython file:
------------------------------------------------------------
...
      'usage_page': c.usage_page,
      'usage': c.usage,
      'interface_number': c.interface_number,
    })
    c = c.next
  hid_free_enumeration(info)
                     ^
------------------------------------------------------------

hid.pyx:41:22: undeclared name not builtin: hid_free_enumeration

Error compiling Cython file:
------------------------------------------------------------
...
              raise MemoryError()
          result = PyUnicode_AsWideChar(serial_number, cserial_number, serial_len)
          if result == -1:
              raise ValueError("invalid serial number string")
          cserial_number[serial_len] = 0  # Must explicitly null-terminate
        self._c_hid = hid_open(vendor_id, product_id, cserial_number)
                             ^
------------------------------------------------------------

hid.pyx:61:30: undeclared name not builtin: hid_open

Error compiling Cython file:
------------------------------------------------------------
...
              raise MemoryError()
          result = PyUnicode_AsWideChar(serial_number, cserial_number, serial_len)
          if result == -1:
              raise ValueError("invalid serial number string")
          cserial_number[serial_len] = 0  # Must explicitly null-terminate
        self._c_hid = hid_open(vendor_id, product_id, cserial_number)
                                                                   ^
------------------------------------------------------------

hid.pyx:61:68: Cannot convert 'wchar_t *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
      if self._c_hid == NULL:
          raise IOError('open failed')

  def open_path(self, bytes path):
      cdef char* cbuff = path
      self._c_hid = hid_open_path(cbuff)
                                ^
------------------------------------------------------------

hid.pyx:70:33: undeclared name not builtin: hid_open_path

Error compiling Cython file:
------------------------------------------------------------
...
      if self._c_hid == NULL:
          raise IOError('open failed')

  def close(self):
      if self._c_hid != NULL:
          hid_close(self._c_hid)
                  ^
------------------------------------------------------------

hid.pyx:76:19: undeclared name not builtin: hid_close

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_write(c_hid, cbuff, c_buff_len)
                         ^
------------------------------------------------------------

hid.pyx:93:26: undeclared name not builtin: hid_write

Error compiling Cython file:
------------------------------------------------------------
...

  def set_nonblocking(self, int v):
      '''Set the nonblocking flag'''
      if self._c_hid == NULL:
          raise ValueError('not open')
      return hid_set_nonblocking(self._c_hid, v)
                               ^
------------------------------------------------------------

hid.pyx:100:32: undeclared name not builtin: hid_set_nonblocking

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
                               ^
------------------------------------------------------------

hid.pyx:117:32: undeclared name not builtin: hid_read_timeout

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
             ^
------------------------------------------------------------

hid.pyx:117:14: Assignment of Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
      else:
        with nogil:
            n = hid_read(c_hid, cbuff, c_max_length)
                       ^
------------------------------------------------------------

hid.pyx:120:24: undeclared name not builtin: hid_read

Error compiling Cython file:
------------------------------------------------------------
...
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
      else:
        with nogil:
            n = hid_read(c_hid, cbuff, c_max_length)
             ^
------------------------------------------------------------

hid.pyx:120:14: Assignment of Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

  def get_manufacturer_string(self):
      if self._c_hid == NULL:
          raise ValueError('not open')
      cdef wchar_t buff[255]
      cdef int r = hid_get_manufacturer_string(self._c_hid, buff, 255)
                                             ^
------------------------------------------------------------

hid.pyx:132:46: undeclared name not builtin: hid_get_manufacturer_string

Error compiling Cython file:
------------------------------------------------------------
...

  def get_product_string(self):
      if self._c_hid == NULL:
          raise ValueError('not open')
      cdef wchar_t buff[255]
      cdef int r = hid_get_product_string(self._c_hid, buff, 255)
                                        ^
------------------------------------------------------------

hid.pyx:140:41: undeclared name not builtin: hid_get_product_string

Error compiling Cython file:
------------------------------------------------------------
...

  def get_serial_number_string(self):
      if self._c_hid == NULL:
          raise ValueError('not open')
      cdef wchar_t buff[255]
      cdef int r = hid_get_serial_number_string(self._c_hid, buff, 255)
                                              ^
------------------------------------------------------------

hid.pyx:148:47: undeclared name not builtin: hid_get_serial_number_string

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_send_feature_report(c_hid, cbuff, c_buff_len)
                                       ^
------------------------------------------------------------

hid.pyx:166:40: undeclared name not builtin: hid_send_feature_report

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      cbuff[0] = report_num
      with nogil:
        n = hid_get_feature_report(c_hid, cbuff, c_max_length)
                                 ^
------------------------------------------------------------

hid.pyx:183:34: undeclared name not builtin: hid_get_feature_report

Error compiling Cython file:
------------------------------------------------------------
...
      return res

  def error(self):
      if self._c_hid == NULL:
          raise ValueError('not open')
      return U(<wchar_t*>hid_error(self._c_hid))
                                 ^
------------------------------------------------------------

hid.pyx:194:34: undeclared name not builtin: hid_error

Error compiling Cython file:
------------------------------------------------------------
...
      return res

  def error(self):
      if self._c_hid == NULL:
          raise ValueError('not open')
      return U(<wchar_t*>hid_error(self._c_hid))
              ^
------------------------------------------------------------

hid.pyx:194:15: Casting temporary Python object to non-numeric non-Python type

Error compiling Cython file:
------------------------------------------------------------
...
      return res

  def error(self):
      if self._c_hid == NULL:
          raise ValueError('not open')
      return U(<wchar_t*>hid_error(self._c_hid))
              ^
------------------------------------------------------------

hid.pyx:194:15: Python objects cannot be cast to pointers of primitive types

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_write(c_hid, cbuff, c_buff_len)
                         ^
------------------------------------------------------------

hid.pyx:93:26: Coercion from Python not allowed without the GIL

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_write(c_hid, cbuff, c_buff_len)
                         ^
------------------------------------------------------------

hid.pyx:93:26: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_write(c_hid, cbuff, c_buff_len)
                         ^
------------------------------------------------------------

hid.pyx:93:26: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_write(c_hid, cbuff, c_buff_len)
                         ^
------------------------------------------------------------

hid.pyx:93:26: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_write(c_hid, cbuff, c_buff_len)
                               ^
------------------------------------------------------------

hid.pyx:93:32: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_write(c_hid, cbuff, c_buff_len)
                                      ^
------------------------------------------------------------

hid.pyx:93:39: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_write(c_hid, cbuff, c_buff_len)
                                                  ^
------------------------------------------------------------

hid.pyx:93:51: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
                               ^
------------------------------------------------------------

hid.pyx:117:32: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
                               ^
------------------------------------------------------------

hid.pyx:117:32: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
                               ^
------------------------------------------------------------

hid.pyx:117:32: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
                                     ^
------------------------------------------------------------

hid.pyx:117:38: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
                                            ^
------------------------------------------------------------

hid.pyx:117:45: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
                                                          ^
------------------------------------------------------------

hid.pyx:117:59: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
                                                                        ^
------------------------------------------------------------

hid.pyx:117:73: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
      else:
        with nogil:
            n = hid_read(c_hid, cbuff, c_max_length)
                       ^
------------------------------------------------------------

hid.pyx:120:24: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
      else:
        with nogil:
            n = hid_read(c_hid, cbuff, c_max_length)
                       ^
------------------------------------------------------------

hid.pyx:120:24: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
      else:
        with nogil:
            n = hid_read(c_hid, cbuff, c_max_length)
                       ^
------------------------------------------------------------

hid.pyx:120:24: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
      else:
        with nogil:
            n = hid_read(c_hid, cbuff, c_max_length)
                             ^
------------------------------------------------------------

hid.pyx:120:30: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
      else:
        with nogil:
            n = hid_read(c_hid, cbuff, c_max_length)
                                    ^
------------------------------------------------------------

hid.pyx:120:37: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      if timeout_ms > 0:
        with nogil:
            n = hid_read_timeout(c_hid, cbuff, c_max_length, c_timeout_ms)
      else:
        with nogil:
            n = hid_read(c_hid, cbuff, c_max_length)
                                                  ^
------------------------------------------------------------

hid.pyx:120:51: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_send_feature_report(c_hid, cbuff, c_buff_len)
                                       ^
------------------------------------------------------------

hid.pyx:166:40: Coercion from Python not allowed without the GIL

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_send_feature_report(c_hid, cbuff, c_buff_len)
                                       ^
------------------------------------------------------------

hid.pyx:166:40: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_send_feature_report(c_hid, cbuff, c_buff_len)
                                       ^
------------------------------------------------------------

hid.pyx:166:40: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_send_feature_report(c_hid, cbuff, c_buff_len)
                                       ^
------------------------------------------------------------

hid.pyx:166:40: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_send_feature_report(c_hid, cbuff, c_buff_len)
                                             ^
------------------------------------------------------------

hid.pyx:166:46: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_send_feature_report(c_hid, cbuff, c_buff_len)
                                                    ^
------------------------------------------------------------

hid.pyx:166:53: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
      cdef hid_device * c_hid = self._c_hid
      cdef unsigned char* cbuff = buff # covert to c string
      cdef size_t c_buff_len = len(buff)
      cdef int result
      with nogil:
        result = hid_send_feature_report(c_hid, cbuff, c_buff_len)
                                                                ^
------------------------------------------------------------

hid.pyx:166:65: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      cbuff[0] = report_num
      with nogil:
        n = hid_get_feature_report(c_hid, cbuff, c_max_length)
                                 ^
------------------------------------------------------------

hid.pyx:183:34: Coercion from Python not allowed without the GIL

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      cbuff[0] = report_num
      with nogil:
        n = hid_get_feature_report(c_hid, cbuff, c_max_length)
                                 ^
------------------------------------------------------------

hid.pyx:183:34: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      cbuff[0] = report_num
      with nogil:
        n = hid_get_feature_report(c_hid, cbuff, c_max_length)
                                 ^
------------------------------------------------------------

hid.pyx:183:34: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      cbuff[0] = report_num
      with nogil:
        n = hid_get_feature_report(c_hid, cbuff, c_max_length)
                                 ^
------------------------------------------------------------

hid.pyx:183:34: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      cbuff[0] = report_num
      with nogil:
        n = hid_get_feature_report(c_hid, cbuff, c_max_length)
                                       ^
------------------------------------------------------------

hid.pyx:183:40: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      cbuff[0] = report_num
      with nogil:
        n = hid_get_feature_report(c_hid, cbuff, c_max_length)
                                              ^
------------------------------------------------------------

hid.pyx:183:47: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
          cbuff = lbuff
      else:
          cbuff = <unsigned char *>malloc(max_length)
      cbuff[0] = report_num
      with nogil:
        n = hid_get_feature_report(c_hid, cbuff, c_max_length)
                                                            ^
------------------------------------------------------------

hid.pyx:183:61: Converting to Python object not allowed without gil
hid.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
oesayan@oesayan-linux:~/python-evic$ 
```

**Comment by Ban3** [comment] 2016-01-14 00:23
I could reproduce this. The issue is the latest version of hidapi. I pushed a fix in 2696daeca5f79ea685. See if that fixes it for you.

This should probably get reported upstream, though.

**Comment by ninefineninja** [comment] 2016-01-14 01:06
Thanks for your work. Pretty sad, but hidusb is broken or something. The fix worked, but another errors are coming.

```
Processing dependencies for evic==0.1
Searching for hidapi==0.7.99.post9
Reading https://pypi.python.org/simple/hidapi/
Best match: hidapi 0.7.99.post9
Downloading https://pypi.python.org/packages/source/h/hidapi/hidapi-0.7.99.post9.tar.gz#md5=4002ddc468edf092e69cd07cfb806440
Processing hidapi-0.7.99.post9.tar.gz
Writing /tmp/easy_install-wE7NnE/hidapi-0.7.99.post9/setup.cfg
Running hidapi-0.7.99.post9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wE7NnE/hidapi-0.7.99.post9/egg-dist-tmp-gwN9DQ
hid.c: In function ‘__pyx_pf_3hid_6device_open’:
hid.c:1400:7: warning: passing argument 1 of ‘PyUnicodeUCS4_AsWideChar’ from incompatible pointer type [enabled by default]
       __pyx_v_result = PyUnicode_AsWideChar(__pyx_v_serial_number, __pyx_v_cserial_number, __pyx_v_serial_len);
       ^
In file included from /usr/include/python2.7/Python.h:85:0,
                 from hid.c:4:
/usr/include/python2.7/unicodeobject.h:246:31: note: expected ‘struct PyUnicodeObject *’ but argument is of type ‘struct PyObject *’
 # define PyUnicode_AsWideChar PyUnicodeUCS4_AsWideChar
                               ^
/usr/include/python2.7/unicodeobject.h:591:24: note: in expansion of macro ‘PyUnicode_AsWideChar’
 PyAPI_FUNC(Py_ssize_t) PyUnicode_AsWideChar(
                        ^
hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
                    ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
oesayan@oesayan-linux:~/python-evic$ 
```

What version of hidapi worked for you?

**Comment by Ban3** [comment] 2016-01-14 01:13
Try this:

```
sudo apt-get install libusb-1.0-0-dev
```

**Comment by Ban3** [comment] 2016-01-14 01:17
Original issue reported in trezor/cython-hidapi#25

**Comment by ninefineninja** [comment] 2016-01-14 01:28
That helped, but there was another error.
Changed the setup.py to

```
requirements = [
    'hidapi==0.7.99_9',
    'click'
]
```

and it finally worked.

Thank you very much for your help.

**Comment by Ban3** [comment] 2016-01-14 01:32
Great! I'll keep this open until the issue is fixed in hidapi.

**Closed as completed** 2016-01-14 15:26 UTC

**Comment by febs** [comment] 2017-09-02 11:26
But then you closed it lol. The issue is still present. Thanks!
