### ISSUE TITLE
Issues installing on ubuntu 15.10

### ISSUE THREAD

**Issue by fairhat** [Ban3/python-evic#5] opened 2016-01-08 22:31 UTC
Hey, might just be me, but i'm stuck between `$ python setup.py install` and running `evic`

I keep getting an error that "evic" does not contain a **main** module. :<

**Comment by Ban3** [comment] 2016-01-09 13:36
Could you post the full output from running setup.py and `evic`?

**Comment by DioCannabinoide** [comment] 2016-01-16 05:39
Ran into the same, output:
http://pastebin.com/4iQuZRGK

I can see it cannot recognise the build

**Comment by Ban3** [comment] 2016-01-16 08:54
Please install setuptools before building and try again.

**Comment by spado92** [comment] 2016-01-16 12:28
Done, but I still get this error:
http://pastebin.com/kiuNPyMd

**Comment by DioCannabinoide** [comment] 2016-01-16 12:56
Made some progress... checked that all dependencies were installed.
Also, I am trying to run two VMs on 14.04 and 15.10 but they both get the error.
Current output:
http://pastebin.com/Rj1kUxqn
http://pastebin.com/JYhBA8dA

Actually, just now I tried running it native on my OS X install and I get the same error.
It must be my n00bness then...

**Comment by ReservedField** [comment] 2016-01-16 13:05
Could you try launching it as `evic` instead of `python evic`? Like `sudo evic dump-dataflash -o out.bin`.

**Comment by Ban3** [comment] 2016-01-16 13:06
@ReservedField is right. Don't put python in front of the command.

**Comment by DioCannabinoide** [comment] 2016-01-16 13:07
Oh wow... See... n00bness, that's what I said.
It's even running on OS X. All these VMs only cause lack of brain.
Anyway keep up the great work, you guys!
Indeed I am trying to get the new Presa 3.0 on the eVic :)

**Comment by fairhat** [comment] 2016-01-16 13:20
Sorry, didn't have time to do it yet, thanks for the info guys, will try it later! :-)

**Comment by DioCannabinoide** [comment] 2016-01-16 13:42
Aaaand... Success!
![img_20160116_144643](https://cloud.githubusercontent.com/assets/16729692/12372710/f8cbe588-bc60-11e5-9945-f957ae923d3a.jpg)
Really, thank you!
I can confirm that now my eVic is Unknown to the Joyetech updater and a Presa 75W to the Wismec one.
I have never really programmed, but this really makes me wanna tinker with it!
I don't even know any C but I'm going to try decrypting the firmwares and see what can be played with.

**Comment by Ban3** [comment] 2016-03-07 13:19
Is this still an issue?

**Comment by ghost** [comment] 2016-04-02 00:06
Wanna share firmware?

**Comment by eliah-w** [comment] 2016-04-02 00:24
@Konsoul3 You can download the Presa firmware from here: http://www.wismec.com/product/presa-tc75w/

Extract the zip. Firmware file is `Presa_TC75W_V3.00.bin`

**Comment by ghost** [comment] 2016-04-02 00:27
@spado92 Thank you :+1:

**Comment by Ban3** [comment] 2016-08-14 00:31
Closing this as original reporter seems to be MIA

**Closed as completed by Ban3** 2016-08-14 00:31 UTC
